import { BookingDoctor } from '../types';
import { getClinicSpecialtyById } from '../../../constants/clinicSpecialties';

const departmentLabel = (specialtyId: string) =>
  getClinicSpecialtyById(specialtyId)?.departmentLabel ?? 'Chuyên khoa';

export const BOOKING_DOCTORS: BookingDoctor[] = [
  {
    id: 'doc-1',
    name: 'BS. Nguyễn Văn A',
    specialtyId: 'cardiology',
    departmentLabel: departmentLabel('cardiology'),
    rating: 4.9,
    reviewCount: 128,
    experienceYears: 15,
    tag: { label: 'Chuyên gia đầu ngành', variant: 'expert' },
    nextAvailableSlot: 'Hôm nay, 14:30',
    isAvailable: true,
    avatarBg: 'rgba(218,226,255,0.3)',
  },
  {
    id: 'doc-2',
    name: 'BS. Trần Minh B',
    specialtyId: 'cardiology',
    departmentLabel: departmentLabel('cardiology'),
    rating: 4.8,
    reviewCount: 95,
    experienceYears: 10,
    tag: { label: 'Tiến sĩ Y khoa', variant: 'phd' },
    nextAvailableSlot: 'Mai, 08:00',
    isAvailable: true,
    avatarBg: 'rgba(255,218,210,0.3)',
  },
  {
    id: 'doc-3',
    name: 'BS. Lê Hoàng C',
    specialtyId: 'cardiology',
    departmentLabel: departmentLabel('cardiology'),
    rating: 5.0,
    reviewCount: 210,
    experienceYears: 22,
    tag: { label: 'Bác sĩ Ưu tú', variant: 'elite' },
    nextAvailableSlot: null,
    isAvailable: false,
    avatarBg: 'rgba(130,249,190,0.3)',
  },
  {
    id: 'doc-4',
    name: 'BS. Phạm Thu D',
    specialtyId: 'musculoskeletal',
    departmentLabel: departmentLabel('musculoskeletal'),
    rating: 4.7,
    reviewCount: 52,
    experienceYears: 8,
    tag: { label: 'Bác sĩ trẻ tiềm năng', variant: 'potential' },
    nextAvailableSlot: 'Hôm nay, 16:00',
    isAvailable: true,
    avatarBg: 'rgba(218,226,255,0.3)',
  },
  {
    id: 'doc-5',
    name: 'BS. Hoàng Văn E',
    specialtyId: 'musculoskeletal',
    departmentLabel: departmentLabel('musculoskeletal'),
    rating: 4.9,
    reviewCount: 143,
    experienceYears: 18,
    tag: { label: 'Chuyên gia đầu ngành', variant: 'expert' },
    nextAvailableSlot: 'Hôm nay, 10:00',
    isAvailable: true,
    avatarBg: 'rgba(255,218,210,0.3)',
  },
  {
    id: 'doc-6',
    name: 'BS. Trần Thị F',
    specialtyId: 'musculoskeletal',
    departmentLabel: departmentLabel('musculoskeletal'),
    rating: 4.6,
    reviewCount: 67,
    experienceYears: 12,
    tag: { label: 'Tiến sĩ Y khoa', variant: 'phd' },
    nextAvailableSlot: 'Mai, 15:30',
    isAvailable: true,
    avatarBg: 'rgba(130,249,190,0.3)',
  },
  {
    id: 'doc-7',
    name: 'BS. Nguyễn Thị G',
    specialtyId: 'obstetrics-pediatrics',
    departmentLabel: departmentLabel('obstetrics-pediatrics'),
    rating: 4.9,
    reviewCount: 186,
    experienceYears: 16,
    tag: { label: 'Chuyên gia đầu ngành', variant: 'expert' },
    nextAvailableSlot: 'Hôm nay, 09:00',
    isAvailable: true,
    avatarBg: 'rgba(255,218,210,0.3)',
  },
  {
    id: 'doc-8',
    name: 'BS. Lê Văn H',
    specialtyId: 'obstetrics-pediatrics',
    departmentLabel: departmentLabel('obstetrics-pediatrics'),
    rating: 4.8,
    reviewCount: 112,
    experienceYears: 14,
    tag: { label: 'Bác sĩ Ưu tú', variant: 'elite' },
    nextAvailableSlot: 'Mai, 11:00',
    isAvailable: true,
    avatarBg: 'rgba(218,226,255,0.3)',
  },
  {
    id: 'doc-8b',
    name: 'BS. Trần Thị M',
    specialtyId: 'obstetrics-pediatrics',
    departmentLabel: departmentLabel('obstetrics-pediatrics'),
    rating: 4.7,
    reviewCount: 89,
    experienceYears: 12,
    tag: { label: 'Tiến sĩ Y khoa', variant: 'phd' },
    nextAvailableSlot: 'Hôm nay, 15:00',
    isAvailable: true,
    avatarBg: 'rgba(130,249,190,0.3)',
  },
  {
    id: 'doc-9',
    name: 'BS. Phạm Hoàng I',
    specialtyId: 'ophthalmology',
    departmentLabel: departmentLabel('ophthalmology'),
    rating: 5.0,
    reviewCount: 210,
    experienceYears: 22,
    tag: { label: 'Bác sĩ Ưu tú', variant: 'elite' },
    nextAvailableSlot: null,
    isAvailable: false,
    avatarBg: 'rgba(130,249,190,0.3)',
  },
  {
    id: 'doc-10',
    name: 'BS. Trần Anh K',
    specialtyId: 'ophthalmology',
    departmentLabel: departmentLabel('ophthalmology'),
    rating: 4.7,
    reviewCount: 78,
    experienceYears: 11,
    tag: { label: 'Bác sĩ trẻ tiềm năng', variant: 'potential' },
    nextAvailableSlot: 'Hôm nay, 16:00',
    isAvailable: true,
    avatarBg: 'rgba(218,226,255,0.3)',
  },
  {
    id: 'doc-11',
    name: 'BS. Võ Minh L',
    specialtyId: 'ophthalmology',
    departmentLabel: departmentLabel('ophthalmology'),
    rating: 4.8,
    reviewCount: 99,
    experienceYears: 13,
    tag: { label: 'Tiến sĩ Y khoa', variant: 'phd' },
    nextAvailableSlot: 'Mai, 14:00',
    isAvailable: true,
    avatarBg: 'rgba(255,218,210,0.3)',
  },
];

export const getDoctorsBySpecialty = (specialtyId: string): BookingDoctor[] =>
  BOOKING_DOCTORS.filter((doctor) => doctor.specialtyId === specialtyId);

export const getDoctorById = (doctorId: string): BookingDoctor | undefined =>
  BOOKING_DOCTORS.find((doctor) => doctor.id === doctorId);

export const getSuggestedDoctor = (specialtyId: string): BookingDoctor | undefined => {
  const doctors = getDoctorsBySpecialty(specialtyId)
    .filter((doctor) => doctor.isAvailable)
    .sort((a, b) => b.rating - a.rating);
  return doctors[0];
};
